#!/usr/bin/env bash
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-gtk
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal-kde
killall xdg-desktop-portal-gnome
killall xdg-desktop-portal-xapp
killall xdg-desktop-portal-lxqt
killall xdg-desktop-portal
sleep 1
/usr/lib/xdg-desktop-portal &
/usr/lib/xdg-desktop-portal-hyprland &
/usr/lib/xdg-desktop-portal-gtk &


